# Generated by Django 2.2.7 on 2019-11-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200, verbose_name='店名')),
                ('urls', models.TextField(max_length=300, verbose_name='URL')),
                ('address', models.TextField(max_length=300, verbose_name='住所')),
                ('genre_name', models.TextField(max_length=300, verbose_name='店のジャンルやキャッチコピー1')),
                ('genre_catch', models.TextField(max_length=300, verbose_name='店のジャンルやキャッチコピー2')),
                ('catch', models.TextField(max_length=300, verbose_name='店のジャンルやキャッチコピー3')),
                ('image_url', models.TextField(max_length=300, verbose_name='画像のURL')),
                ('insta_tag_name', models.TextField(max_length=300, verbose_name='インスタのタグ名')),
                ('budget', models.IntegerField(
                    choices=[(0, '1001~2000'), (1, '2001~3000'), (2, '3001~4000'), (3, '4001~5000'), (4, '5001~6000')],
                    default=1, verbose_name='予算')),
                ('budget_str', models.TextField(max_length=300, verbose_name='予算str')),
                ('area', models.IntegerField(choices=[(0, '名古屋駅'), (1, '栄駅')], default=1, verbose_name='エリア')),
                ('area_str', models.TextField(max_length=300, verbose_name='エリアstr')),
                ('map_shop', models.TextField(max_length=300, verbose_name='ショップの位置情報')),
                ('map_station', models.TextField(max_length=300, verbose_name='駅の位置情報')),
                ('good', models.IntegerField(default=0, verbose_name='エリア')),
            ],
            options={
                'verbose_name': 'アイテム',
                'verbose_name_plural': 'アイテム',
            },
        ),
    ]
